### ISSUE TITLE
[Proposal] Docs link should link elsewhere

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/universal-blue-org#26]
https://docs.universal-blue.org/ should link to https://universal-blue.discourse.group/docs?topic=3147 since it includes the official documentation.  Discourse users write up new support posts and label it incorrectly as 'documentation' on almost a monthly basis.

**Comment by xynydev** [comment]
+1 (or +1000000 if possible). https://universal-blue.discourse.group/docs?topic=3147 is a good docs starting page, it is clear and provides some sort of structure for reading documentation. https://universal-blue.discourse.group/docs is way too cluttered and IME easy to give up on. IMHO also the Discourse sidebar docs link should be to https://universal-blue.discourse.group/docs?topic=3318

**Comment by NiHaiden** [comment]
I agree with this proposal!

**Comment by nicknamenamenick** [comment]
this proposal is most likely going to die soon... RIP

**Comment by nicknamenamenick** [comment]
Actually...

**Comment by xynydev** [comment]
Why was this closed as completed when it was not in fact completed? There are no objections, this seems just an oversight from the domain owner (not sure who).
